### ISSUE TITLE
Geo predicates wiki

### ISSUE THREAD

**Issue by eliotjordan** [projecthydra-labs/geo_concerns#170]
Create wiki doc listing geo specific predicates that are used in GeoConcerns. Requested by @tpendragon and the Hydra URI Management Working Group.

**Comment by eliotjordan** [comment]
Let's take another look at projection​ predicate.

**Comment by johnhuck** [comment]
DCMI Box encoding scheme also accommodates recording projection. Would that be a solution? http://dublincore.org/documents/dcmi-box/

**Comment by eliotjordan** [comment]
@johnhuck What we want, I think, is just the projection bit. It seems to me that dcmi-box describes the projection of the bounding box not necessarily the projection of the underlying dataset. This is quite common. I suppose what I meant, is, does there exist a predicate/vocabulary that describes projection that we can use out of the box. Or is it like it like geospatial file format, and we'll have to cobble something together ourselves.

**Comment by eliotjordan** [comment]
@johnhuck  I'm sure you've seen this, but EPSG is a comprehensive, and industry standard list of f coordinate reference systems. Is there a linked data vocab that already uses this list? If not, then perhaps we can build one. This one is easier than file format, because ESPG is exhaustive. Not entirely complete I'm sure, but pretty darn close I'd bet.  

http://spatialreference.org/ref/epsg/4326/

**Comment by johnhuck** [comment]
Since EPSG assigns URNs to manage different projections, what they are maintaining is already a controlled vocabulary, so there wouldn't be a need to make a different one. As least as far as RDF is concerned, a URN is a URI and can be used anywhere a URI is required.  But if we used bf:projection, whose range is rdfs:Literal, its URI status would be irrelevant, except as an unambiguous identifier, which could perhaps be repurposed later. Several online services like the one you mention seem to provide the value-added service of a URL for the terms. This one supplies the GML metadata for the projection, but I think it's a third-party offering: https://epsg.io/4326.gml

**Comment by johnhuck** [comment]
Added a wiki page with a basic table. Needs more information.

**Comment by eliotjordan** [comment]
We have the basic wiki. I think we can close this issue.

**Comment by johnhuck** [comment]
Agreed.
