### ISSUE TITLE
Work out how to create, attach, and link related objects

### ISSUE THREAD

**Issue by eliotjordan** [projecthydra-labs/geo_concerns#36]
Work out how to create, attach, and link related objects. Sketch out how this will look on the screen.

Are there examples from other Hydra projects to follow?

**Comment by yulgit1** [comment]
Was checking out the app with the latest source code, 2 things:

1) (trivial task)Hydra::Works references should be refactored from GenericFile to FileSet
2) Regardless of (1), the upload "Add Your Content" in the ImageWorks.new (and other Works new ) screen just create generic FileSets rather than (as the case is for ImageWorks) leverage the FileSets defined distinctly for the scanned image, and metadata file(s),and link to the rasterWorks controller.

Will look into it further.

**Comment by eliotjordan** [comment]
@yulgit1 Thanks for looking at this. I'm putting the final touches on a proposal to help with this issue. I'll send out an email to the WG once the PR is posted. It does involve a change to the model, so we'll need some group discussion.

**Comment by yulgit1** [comment]
Submitted pull request for (1) above.
https://github.com/projecthydra-labs/geo_concerns/pull/67/

But I think there are larger foundational issues.  I stumbled across this comment in image_files_controller.rb:

# Generated via
#  `rails generate curation_concerns:work ImageFile`

But I don't think this should be a work, but rather a file_set.  The same applies for ImageFile, RasterFile, VectorFile, ExternalMetadataFile (although I'm not sure why there aren't routes for these). But starting to think the whole suite of files created by the work generator really don't apply here and perhaps should be eliminated:

spec/models/#{file_name}_spec.rb
app/models/#{file_name}.rb
spec/controllers/curation_concerns/#{plural_file_name}_controller_spec.rb
spec/actors/curation_concerns/#{file_name}_actor_spec.rb
spec/forms/curation_concerns/#{file_name}_form_spec.rb
app/controllers/curation_concerns/#{plural_file_name}_controller.rb
app/actors/curation_concerns/#{file_name}_actor.rb
app/forms/curation_concerns/#{file_name}_form.rb
config/initializers/curation_concerns.rb
app/views/#{plural_file_name}/_#{file_name}.html.erb

 with exceptions:

1) The models, for example, as these are the hooks into the work Darren did with the external metadata extraction
2) The controller, perhaps  with the change that it subclass file_sets_controller_behavior, rather than the curation_concern_controller behavior (that applies to the work) and have actionable routes.

Not sure how to get there yet, but I think the desired behavior is to:

1) Register the file_set types somehow with its parent work.
2) leverage subclassed file_sets_controllers to list and upload ( GET and POST) the distinguished file types within the Works interfaces.

There is also the issue of how to interface the work->work relationship (like vectors belonging to rasters), but will save that for a different day.

Does this make sense? I might be diving off the deep end.  But if they do, they might be issues best addressed with changes to curation concerns itself (like create a file_set generator), rather custom classes directly in the geo_concerns fork?
