### ISSUE TITLE
Export to Geoblacklight

### ISSUE THREAD

**Issue by eliotjordan** [projecthydra-labs/geo_concerns#70]
Have an endpoint that export the item into geoblacklight schema

**Comment by drh-stanford** [comment]
See https://github.com/geoblacklight/geoblacklight-schema/issues/80

**Comment by jrgriffiniii** [comment]
As I currently understand the GeoBlacklight schema and this issue, the ActiveFedora ID for the FileSet or Image/Raster/VectorWork must map to the Solr field "uuid".

Unfortunately, I receive the following error when I attempt to implement a solution for this:
```
Error: {'responseHeader'=>{'status'=>400,'QTime'=>2},'error'=>{'msg'=>'ERROR: [doc=ws859f68w] unknown field \'uuid\'','code'=>400}}
```
(Please see the latest [WIP] commit)

My suspicion is that Solrizer uses dynamic fields in order to avoid hard-coding fields generated for indexed ActiveFedora properties (explaining why one finds field names such as "dct_references_s" rather than simply "dct_references", as a common pattern for dynamic fields would be "*_s" for single valued strings).  Because GeoBlacklight requires "uuid" rather than "uuid_s", I can only propose that we proceed by offering an alternative/extended Solr schema.

I will further investigate this and report my findings.  Please let me know if any of my suspicions rest upon some misunderstanding of Solrizer, the GeoBlacklight schema, or ActiveFedora.

**Comment by drh-stanford** [comment]
Note that the GeoBlacklight schema went 1.0. See the wiki for details: https://github.com/geoblacklight/geoblacklight/wiki/Schema

**Comment by drh-stanford** [comment]
Pending #170

**Comment by drh-stanford** [comment]
See https://github.com/projecthydra-labs/geo_concerns/blob/master/app/services/geo_concerns/discovery/geoblacklight_document.rb

**Comment by drh-stanford** [comment]
I have a branch going, but I have a question. How do I make an attribute a single valued attribute? Right now, `provenance` is an Array, but I cannot find *where* it thinks that from.

https://github.com/projecthydra-labs/geo_concerns/blob/70-geoblacklight-schema-v1/app/models/concerns/geo_concerns/solr_document_behavior.rb#L22
https://github.com/projecthydra-labs/geo_concerns/blob/8d34965f738a82590897d453d41a599a02022ff1/app/schemas/geo_concerns/basic_geo_metadata_required.rb#L23

**Comment by eliotjordan** [comment]
I'm not sure why, but it looks like you have to do some custom indexing to get that to happen. As it stands, the UI only allows one `provenance` value. Don't think we need to reinvent the wheel here.

https://github.com/projecthydra/curation_concerns/blob/master/app/indexers/curation_concerns/collection_indexer.rb#L12

**Comment by eliotjordan** [comment]
Also related is issue #169. I think we might want to use a configurable institution name here to generate the geoblacklight docs instead of provenance. We may not need that property at all.

**Comment by johnhuck** [comment]
there's also that new :depositor attribute, but I dunno how it's used in cc.

**Comment by drh-stanford** [comment]
I don't understand the link to the collection_indexer.rb. Can you clarify?

**Comment by eliotjordan** [comment]
@drh I got confused there. That is not the droid you are looking for.

**Comment by eliotjordan** [comment]
@johnhuck The :depositor attr looks like it is auto-populated with the username of the person creating the work. I think this is to support sufia/ir applications.

**Comment by johnhuck** [comment]
👍  makes sense.
